### ISSUE TITLE
How to remove cached input stream when using Z_NO_FLUSH

### ISSUE THREAD

**Issue by luhc300** [timotejroiko/fast-zlib#1]
I coded as the example says, using Z_NO_FLUSH option to cache input in blocks, then using Z_SYNC_FLUSH to get results.
However, when I try to make another compression, I found that the inputs in previous compression are still cached in deflate instance. So how to removed the cached results and start a new compression?

**Comment by timotejroiko** [comment]
Hello, its seems to be a bug, should be fixed now in v2.0.1, thanks for reporting!
